name: linting

on: [push,workflow_dispatch]
jobs:
  linting:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - name: cpp-check
        uses: tonybaloney/cppcheck-action@master
