name: linting

on: [push,workflow_dispatch]
jobs:
  linting:
    name: cppcheck
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls
      - name: cpp-check
        uses: deep5050/cppcheck-action@main
