name: linting

on: [push,workflow_dispatch]
jobs:
  checkout:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout
  linting:
    name: cppcheck
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - run: pwd
      - run: ls
      - name: cpp-check
        uses: deep5050/cppcheck-action@main
