name: linting

on: [push]
jobs:
  linting:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: cpp-check
        uses: tonybaloney/cppcheck-action@master
