name: A workflow for my Hello World file
on: [push,workflow_dispatch]

jobs:
  setup:
    name: setup
    steps:
      - run: echo setup
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
      - name: echo
        run: echo Hello
      - uses: ./action-a
        with:
          MY_NAME: "Foo"
