name: A workflow for my Hello World file
on: [push,workflow_dispatch]

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo setup
      - run: echo error > /dev/stderr
      - run: exit 1
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
  cleanup:
    name: cleanup
    runs-on: ubuntu-latest
    steps:
      - run: echo cleanup
