name: test
on: [push,workflow_dispatch]

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
      - uses: actions/checkout@v1
      - run: echo ::warn file=main.cpp,line=3,col=1::hello world
